### ISSUE TITLE
Support for multiple 'To' addresses?

### ISSUE THREAD

**Issue by reinvented** [Znarkus/postmark-php#1]
The [Postmark API Documentation](http://developer.postmarkapp.com/developer-build.html#message-format) says, in reference to the 'To' field:

> You can pass multiple recipient addresses in the ‘To’ field and the optional ‘Cc’ and ‘Bcc’ fields. Separate multiple addresses with a comma. Note that Postmark has a limit of twenty recipients per message in total. You need to take care not to exceed that limit. Otherwise you will get an error. 

It seems like Postmark.php (and, by association, the [Postmark Drupal Module](http://drupal.org/project/postmark)), only supports a _single_ 'To' address.

If I set the 'To' address with:

```
$email->to('test@example.com,test@example.com');
```

an exception is thrown:

```
Fatal error: Uncaught exception 'Exception' with message 'Invalid to address ''test@example.com,test@example.com'' in Postmark.php:230
```

**Comment by Znarkus** [comment]
Sorry, there is no support for that yet.

**Comment by reinvented** [comment]
I hacked together a fork (http://github.com/reinvented/postmark-php) to serve my own need for this. I needed to remove 'To' address validation and I otherwise simply copied the 'To' handling from your existing 'Cc' handling.

**Comment by greggles** [comment]
Why isn't there support for that? It seems pretty important...

**Comment by Znarkus** [comment]
Don't think there was support for it initially, and I haven't noticed that they've added it. What's the difference between using multiple To addresses and CC?
I will add support for it.

**Comment by greggles** [comment]
From a theoretical perspective, there is no difference.

But when trying to integrate Postmark into existing systems where changing the upstream code can takes weeks or months for a patch to be accepted it's an important difference.

Great news that you're willing to support this mode! I look forward to being able to use Postfix on our server.

**Comment by Znarkus** [comment]
Of course, since it's supported by Postmark. If you're on Forrst, I'd appreciate if you took a look at http://forr.st/~hU2

**Comment by luketsimmons** [comment]
Is there a possibility we could get reinvented's changes rolled into the original Postmark-php? Sort of need the changes for the next release of the Drupal module and it's probably best if one copy is maintained, agreed? btw have signed up for a Forrst account so happy to discuss feedback and bits on there too

**Comment by Znarkus** [comment]
I've started the work on the next release, it should be done next week, since I'm going away over the weekend.

This release should catch up with all new features, and also make some other changes like error handling.

Thanks for your patience!

**Comment by Znarkus** [comment]
The next release is almost ready. I'm waiting for http://help.postmarkapp.com/discussions/questions/314-attachments-and-certificates, and will hopefully release tomorrow.
