### ISSUE TITLE
Fix class_exists() to work with autoloaders

### ISSUE THREAD

**Issue by bolchowka** [Znarkus/postmark-php#11]
You should add a second parameter to this code:

``` php
if (class_exists('Mail_Postmark_Adapter'))
```

so that is becomes:

``` php
if (class_exists('Mail_Postmark_Adapter', false))
```

Otherwise, if you use the Postmark class in your project that already supports __autoload() function, it will try to find this class on his own and will most ceirtanly fail (at least in Zend Framework which looks up PHP classes based on their names).

**Comment by Znarkus** [comment]
Thanks, I will add it to the next version.
