### ISSUE TITLE
Not clearing the email data anywhere in postmark.php

### ISSUE THREAD

**Issue by jpmartin24** [Znarkus/postmark-php#13]
Not clearing the email data anywhere in postmark.php.  Need a  method to clear all email data like 'ClearAddresses()' in phpmailer class

**Comment by Znarkus** [comment]
When do you need to do this? Do you need to clear all data or just the email addresses?

**Comment by jpmartin24** [comment]
Issue is that when multiple recipients are there, first recipients getting mail twice. Yes I need to clear the email addresses after every sending. When i clear the '$_to' array, problem solved.

**Comment by Znarkus** [comment]
Okay, please see https://github.com/Znarkus/postmark-php/issues/6
