### ISSUE TITLE
Suppress InvalidArgumentException Fatal Error in DEBUG_RETURN Mode

### ISSUE THREAD

**Issue by andrewspear** [Znarkus/postmark-php#18]
When an email address is invalid a fatal InvalidArgumentException error is thrown (line 443).  This behaviour is expected when using debug(Mail_Postmark::DEBUG_VERBOSE) not but when using debug(Mail_Postmark::DEBUG_RETURN).

I would suggest that when using debug(Mail_Postmark::DEBUG_RETURN) the error should be returned as an array not output as a fatal error.

**Comment by Znarkus** [comment]
Using an invalid email address is a fatal error, and if we don't handle it, Postmarkapp will return an error. Debug mode is for debugging the HTTP communcation with Postmarkapp. Sorry if this was unclear in the docs.

I encourage you to either catch the exception, or validate the address prior to creating the email.
