### ISSUE TITLE
Email Validation is in error

### ISSUE THREAD

**Issue by pixeloution** [Znarkus/postmark-php#3]
Hi, I noticed you updated your RegEx to validate emails, but the one you use fails on some basic legitimate email addresses such as "hellothere"@example.com - I would recommend using the library available from http://www.dominicsayers.com/isemail/  for the most comprehensive/correct email validation

**Comment by Znarkus** [comment]
Thanks for your feedback!

I'm having a hard time including a email validation library that is actually larger than the main class.

I could instead make it possible to override the default validation with the Adapter, and add a note in the docs.
