### ISSUE TITLE
Support for batch sending

### ISSUE THREAD

**Issue by ruudk** [Znarkus/postmark-php#8]
Would love to see support for batch sending. Do you have this planned already?

**Comment by Znarkus** [comment]
Haven't planned it, but it should be added :) Don't know when yet though

**Comment by ruudk** [comment]
Maybe I'll look into it later

Would be cool to have something like this:

```
<?php
$email = new Mail_Postmark();
$email->startBatch();

$email->addTo('address@example1.com', 'Name')
    ->subject('Subject')
    ->messagePlain('Mail 1')
    ->send();

$email->addTo('address@johndoe.com', 'Name')
    ->subject('Subject')
    ->messagePlain('Mail 2')
    ->send();

$email->sendBatch();
?>
```

What do you think? Do you have a better approach?

**Comment by Znarkus** [comment]
I haven't put much thought into it, but that looks doable. Another way might be to have a Mail_Postmark_Batch class, to separate it.

```
$batch = new Mail_Postmark_Batch();
$batch->add(Mail_Postmark::compose()...);
$batch->add(Mail_Postmark::compose()...);
$batch->add(Mail_Postmark::compose()...);
$batch->send();
```

**Comment by ruudk** [comment]
I like your approach more... now all I need is to find time to implement it.

**Comment by Znarkus** [comment]
Would you do that? That would be excellent :)
